# This is a basic workflow to help you get started with Actions 

name: CI 

# Controls when the action will run. Triggers the workflow on push or pull request   
# events but only for the master branch
on:
  issues:
    types: [opened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
  
    
    strategy:
      matrix:
        commit_ind: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
#         commit_ind: [0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Checkout repository_mining
      uses: actions/checkout@v2
      with:
        repository: amir9979/repository_mining
        path: .
        fetch-depth: 0
    
    - name: Checkout javadiff
      uses: actions/checkout@v2
      with:
        repository: amir9979/javadiff
        path: ./javadiff
        fetch-depth: 0

    - name: Checkout tools repo
      continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.issue.title}}
        path: ./my-tools
        fetch-depth: 0
        
    - name: fetch  
      continue-on-error: true
      run: git fetch
      working-directory: ./my-tools
      
    - name: Checkout caching
      uses: actions/checkout@v2
      with:
        repository: amir9979/caching
        path: ./caching
        fetch-depth: 0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 
        pip install gitpython
        pip install jira
        pip install termcolor 
        pip install openpyxl  
        pip install javalang
        pip install pathlib
        pip install junitparser
        pip install python-bugzilla
        pip install psutil
        pip install -r requirements.txt
        pip install lizard
    - name: javadiff_install
      run: python ./javadiff/setup.py install

    - name: echo
      run: echo 123 > repository_data\r.txt

    - name: longpaths
      run: git config --system core.longpaths true

    - name: ls
      run: ls -R
      
    - name: execute
      run: python main_shir.py ${{ matrix.commit_ind }} 100

    - name: ls files
      run: ls -R

    - name: Upload repository_data
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: repository_data
        # A file, directory or wildcard pattern that describes what to upload
        path: repository_data

    - name: Close Issue
      continue-on-error: true
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
          The extracted data can be found at releases.
